### PR TITLE
Updatemyprofiles

### PR DESCRIPTION
**Pull request by mohabashraf**
@omaressameldin @bassemmagdy @omarelhariry @MohammedAnsary

### CODE REVIEW

**Comment by bassemmagdy** [comment]
@mohabashraf  
1) Inside the Gemfile please write your documentation before adding the gems not after them (line 4).
2)app/assets/stylesheets/application.css you added a block which has not any code (line 279).
3)app/controllers/application_controller.rb please describe the things u added to the class (line 12).
4)app/models/user.rb (line 3) the documentation before the code  and (line 22) the same problem.
5)app/uploaders/avatar_uploader.rb remove all the commented parts w just need a simple description for you code snippet.
6)app/views/devise/confirmations/new.html.erb this class has no documentation !
7)app/views/devise/registrations/edit.html.erb documentation before not after and check your typos.
8)db/migrate/20150320035247_add_avatar_to_users.rb  this class has no documentation !

**Comment by mohabashraf** [comment]
@bassemmagdy @MohammedAnsary  @omaressameldin @omarelhariry

**Comment by mohabashraf** [comment]
@bassemmagdy @MohammedAnsary @omaressameldin @omarelhariry

**Comment by mohabashraf** [comment]
@bassemmagdy

**Comment by mohabashraf** [comment]
@MohammedAnsary @omaressameldin @omarelhariry

**Comment by mohabashraf** [comment]
@omarelhariry @omaressameldin

**Pull request merged**
