### PR TITLE
#15 #20 add view article and delete article options for users and modera...

### PR DESCRIPTION
**Pull request by omaressameldin**
...tors respectively and also add cancan authentication

### CODE REVIEW

**Comment by omaressameldin** [comment]
@AndrewMagdy  @mayarali @bassemmagdy @omarelhariry

**Comment by bassemmagdy** [comment]
@omaressameldin  1)there is typo in line 26 articles/showhtml.erb the commented part second line "bttons"and third line in (he/seh )
2) another typo (rescare)  4th line articles controller.
3)ability.rb line 1 after the comma

**Comment by AndrewMagdy** [comment]
If condition for null image is not needed
first name and last name shouldn't use .htmlsafe as it poses a security risk and is not needed

**Comment by mayarali** [comment]
@omaressameldin  The sequence diagram for S05.
The user doesn't click on view articles from the Article View. It's from landing page and after it is confirmed that it is valid it should be viewed in the Article View

**Comment by mayarali** [comment]
@omaressameldin  In sequence diagram 43.
You check for user's access (moderator) should be between the article controller and model and the result is returned to view in both cases.

**Pull request merged**
